# Generated by Django 5.2.15 on 2026-06-28 10:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Transaction title', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transaction_type', models.CharField(choices=[('income', 'Kirim (Income)'), ('expense', 'Chiqim (Expense)')], help_text='Type of transaction: income or expense', max_length=10)),
                ('category', models.CharField(help_text='Transaction category (e.g., Food, Salary, Rent)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the transaction', null=True)),
                ('date', models.DateField(help_text='Date of transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when transaction was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when transaction was last updated')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='transaction_created_300c15_idx'), models.Index(fields=['transaction_type'], name='transaction_transac_09d7ec_idx'), models.Index(fields=['date'], name='transaction_date_ad8c94_idx')],
            },
        ),
    ]
