# Generated by Django 5.2.15 on 2026-07-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_category_currency_financeaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeaccount',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
